fix: Remove github dependencies

diff --git a/AnimeTagger/Dockerfile b/AnimeTagger/Dockerfile
--- a/AnimeTagger/Dockerfile
+++ b/AnimeTagger/Dockerfile
@@ -4,8 +4,8 @@ LABEL authors="orbital"
 WORKDIR /app
 
 # Install grpc-health-probe
-ADD https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.14/grpc_health_probe-linux-amd64 /bin/grpc_health_probe
-RUN chmod +x /bin/grpc_health_probe
+# ADD https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.14/grpc_health_probe-linux-amd64 /bin/grpc_health_probe
+# RUN chmod +x /bin/grpc_health_probe
 
 COPY requirements.txt .
 RUN pip install --no-cache-dir -r requirements.txt
@@ -14,7 +14,7 @@ EXPOSE 50051
 
 COPY . .
 
-HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
-  CMD grpc_health_probe -addr=:50051 || exit 1
+#HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
+#$  CMD grpc_health_probe -addr=:50051 || exit 1
 
 ENTRYPOINT ["python", "main.py"]
